ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CATEGORY_PURGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DATA_COLLECTION_ARCHIVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DATA_COLLECTION_RESTORED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DATA_COLLECTION_PURGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DOCUMENT_PURGED';
